import {
    EquilibriumSolution,
    SystemConfig,
    ContinuationBranchData,
    ContinuationEigenvalue,
    EquilibriumManifold1DSettings,
    EquilibriumManifold1DResult,
    EquilibriumManifold2DSettings,
    EquilibriumManifold2DResult,
    LimitCycleManifold2DSettings,
    LimitCycleManifold2DResult,
    LimitCycleBranchResponse,
    LimitCycleMeta,
    ContinuationProgress,
    AnalysisProgress,
    EquilibriumSolveProgress,
    CollocationAdaptationReport
} from "./types";
import type { ComputedNormalForm, HopfHopfNormalForm, ZeroHopfNormalForm } from './normal-form-types';

export type CovariantLyapunovResponse = {
    dimension: number;
    checkpoints: number;
    times: number[];
    vectors: number[];
};

export type EquilibriumContinuationRunner = {
    run_steps(batchSize: number): ContinuationProgress;
    get_progress(): ContinuationProgress;
    is_done(): boolean;
    get_result(): ContinuationBranchData;
};

export type ContinuationRunner = {
    run_steps(batchSize: number): ContinuationProgress;
    get_progress(): ContinuationProgress;
    is_done(): boolean;
    get_result(): ContinuationBranchData;
    get_adaptation_report?(): CollocationAdaptationReport;
};

export type Codim1CurveRunner = {
    run_steps(batchSize: number): ContinuationProgress;
    get_progress(): ContinuationProgress;
    is_done(): boolean;
    get_result(): any;
    get_adaptation_report?(): CollocationAdaptationReport;
};

export type ManifoldRunner<T> = {
    run_steps(batchSize: number): ContinuationProgress;
    get_progress(): ContinuationProgress;
    is_done(): boolean;
    get_result(): T;
};

export type AnalysisRunner<T> = {
    run_steps(batchSize: number): AnalysisProgress;
    get_progress(): AnalysisProgress;
    is_done(): boolean;
    get_result(): T;
};

export type EquilibriumSolverRunner = {
    run_steps(batchSize: number): EquilibriumSolveProgress;
    get_progress(): EquilibriumSolveProgress;
    is_done(): boolean;
    get_result(): EquilibriumSolution;
};

export type ForkWasmModule = typeof import("../../crates/fork_wasm/pkg/fork_wasm");
export type GeneratedWasmSystem = InstanceType<ForkWasmModule["WasmSystem"]>;
type WasmSystem = GeneratedWasmSystem & {
    continue_limit_cycle_from_hopf?: (
        hopfState: Float64Array,
        hopfParam: number,
        parameterName: string,
        methodRequest: unknown,
        amplitude: number,
        settings: unknown,
        forward: boolean
    ) => unknown;
    extend_limit_cycle_branch?: (
        branchData: unknown,
        parameterName: string,
        meta: LimitCycleMeta,
        settings: unknown,
        forward: boolean
    ) => unknown;
};

// We use require to load the WASM bindings generated by wasm-pack target nodejs
let wasmModule: ForkWasmModule | undefined;

try {
    // Path relative to compiled index.js in dist/
    // Source is in cli/src, compiled to cli/dist
    // WASM pkg is in ../crates/fork_wasm/pkg
    wasmModule = require("../../crates/fork_wasm/pkg/fork_wasm.js") as ForkWasmModule;
} catch (e) {
    console.warn("Could not load WASM module. Simulation will fail.", e);
}

function periodicPeriodsForConfig(config: SystemConfig): number[] {
    return config.varNames.map((_, index) => {
        const entry = config.periodicVariables?.[index];
        return entry?.enabled && Number.isFinite(entry.period) && entry.period > 0
            ? entry.period
            : Number.NaN;
    });
}

export class WasmBridge {
    instance: WasmSystem;
    private readonly config: SystemConfig;

    constructor(config: SystemConfig) {
        if (!wasmModule) throw new Error("WASM module not loaded");

        const { equations, params, paramNames, varNames, solver, type } = config;
        const systemType = type || "flow";

        this.config = {
            ...config,
            equations: [...equations],
            params: [...params],
            paramNames: [...paramNames],
            varNames: [...varNames],
            periodicVariables: config.periodicVariables?.map((entry) => ({ ...entry }))
        };

        this.instance = new wasmModule.WasmSystem(
            equations,
            new Float64Array(params),
            paramNames,
            varNames,
            solver,
            systemType
        ) as WasmSystem;
        this.instance.set_periods(new Float64Array(periodicPeriodsForConfig(this.config)));
    }

    createEquilibriumContinuationRunner(
        equilibriumState: number[],
        parameterName: string,
        mapIterations: number,
        settings: any,
        forward: boolean
    ): EquilibriumContinuationRunner {
        if (!wasmModule) throw new Error("WASM module not loaded");

        return new wasmModule.WasmEquilibriumRunner(
            this.config.equations,
            new Float64Array(this.config.params),
            this.config.paramNames,
            this.config.varNames,
            this.config.type || "flow",
            mapIterations,
            new Float64Array(equilibriumState),
            parameterName,
            settings,
            forward,
            new Float64Array(periodicPeriodsForConfig(this.config))
        ) as EquilibriumContinuationRunner;
    }

    createLimitCycleContinuationRunner(
        setup: any,
        parameterName: string,
        settings: any,
        forward: boolean
    ): ContinuationRunner {
        if (!wasmModule) throw new Error("WASM module not loaded");

        return new wasmModule.WasmLimitCycleRunner(
            this.config.equations,
            new Float64Array(this.config.params),
            this.config.paramNames,
            this.config.varNames,
            this.config.type || "flow",
            setup,
            parameterName,
            settings,
            forward
        ) as ContinuationRunner;
    }

    createEquilibriumManifold1DRunner(
        equilibriumState: number[],
        settings: EquilibriumManifold1DSettings,
        mapIterations?: number
    ): ManifoldRunner<EquilibriumManifold1DResult> {
        if (!wasmModule) throw new Error("WASM module not loaded");
        if (typeof wasmModule.WasmEqManifold1DRunner !== 'function') {
            throw new Error(
                "Equilibrium 1D manifold runner is unavailable in this WASM build. Rebuild fork_wasm with `wasm-pack build --target nodejs`."
            );
        }
        const iterations =
            this.config.type === "map"
                ? Math.max(1, Math.trunc(mapIterations ?? 1))
                : 1;

        return new wasmModule.WasmEqManifold1DRunner(
            this.config.equations,
            new Float64Array(this.config.params),
            this.config.paramNames,
            this.config.varNames,
            this.config.type || "flow",
            iterations,
            new Float64Array(equilibriumState),
            settings,
            new Float64Array(periodicPeriodsForConfig(this.config))
        ) as ManifoldRunner<EquilibriumManifold1DResult>;
    }

    createEquilibriumManifold1DExtensionRunner(
        branchData: ContinuationBranchData,
        settings: EquilibriumManifold1DSettings,
        mapIterations?: number
    ): ManifoldRunner<ContinuationBranchData> {
        if (!wasmModule) throw new Error("WASM module not loaded");
        if (typeof wasmModule.WasmEqManifold1DExtensionRunner !== 'function') {
            throw new Error(
                "Equilibrium 1D manifold extension runner is unavailable in this WASM build. Rebuild fork_wasm with `wasm-pack build --target nodejs`."
            );
        }
        const iterations =
            this.config.type === "map"
                ? Math.max(1, Math.trunc(mapIterations ?? 1))
                : 1;

        return new wasmModule.WasmEqManifold1DExtensionRunner(
            this.config.equations,
            new Float64Array(this.config.params),
            this.config.paramNames,
            this.config.varNames,
            this.config.type || "flow",
            iterations,
            branchData,
            settings,
            new Float64Array(periodicPeriodsForConfig(this.config))
        ) as ManifoldRunner<ContinuationBranchData>;
    }

    createEquilibriumManifold2DRunner(
        equilibriumState: number[],
        settings: EquilibriumManifold2DSettings
    ): ManifoldRunner<EquilibriumManifold2DResult> {
        if (!wasmModule) throw new Error("WASM module not loaded");
        if (typeof wasmModule.WasmEqManifold2DRunner !== 'function') {
            throw new Error(
                "Equilibrium 2D manifold runner is unavailable in this WASM build. Rebuild fork_wasm with `wasm-pack build --target nodejs`."
            );
        }

        return new wasmModule.WasmEqManifold2DRunner(
            this.config.equations,
            new Float64Array(this.config.params),
            this.config.paramNames,
            this.config.varNames,
            this.config.type || "flow",
            new Float64Array(equilibriumState),
            settings
        ) as ManifoldRunner<EquilibriumManifold2DResult>;
    }

    createManifold2DExtensionRunner(
        branchData: ContinuationBranchData,
        settings: EquilibriumManifold2DSettings | LimitCycleManifold2DSettings
    ): ManifoldRunner<ContinuationBranchData> {
        if (!wasmModule) throw new Error("WASM module not loaded");
        if (typeof wasmModule.WasmManifold2DExtensionRunner !== 'function') {
            throw new Error(
                "2D manifold extension runner is unavailable in this WASM build. Rebuild fork_wasm with `wasm-pack build --target nodejs`."
            );
        }

        return new wasmModule.WasmManifold2DExtensionRunner(
            this.config.equations,
            new Float64Array(this.config.params),
            this.config.paramNames,
            this.config.varNames,
            this.config.type || "flow",
            branchData,
            settings
        ) as ManifoldRunner<ContinuationBranchData>;
    }

    createLimitCycleManifold2DRunner(
        cycleState: number[],
        ntst: number,
        ncol: number,
        floquetMultipliers: ContinuationEigenvalue[],
        settings: LimitCycleManifold2DSettings
    ): ManifoldRunner<LimitCycleManifold2DResult> {
        if (!wasmModule) throw new Error("WASM module not loaded");
        if (typeof wasmModule.WasmCycleManifold2DRunner !== 'function') {
            throw new Error(
                "Limit-cycle 2D manifold runner is unavailable in this WASM build. Rebuild fork_wasm with `wasm-pack build --target nodejs`."
            );
        }

        return new wasmModule.WasmCycleManifold2DRunner(
            this.config.equations,
            new Float64Array(this.config.params),
            this.config.paramNames,
            this.config.varNames,
            this.config.type || "flow",
            new Float64Array(cycleState),
            Math.max(1, Math.trunc(ntst)),
            Math.max(1, Math.trunc(ncol)),
            floquetMultipliers,
            settings
        ) as ManifoldRunner<LimitCycleManifold2DResult>;
    }

    runEquilibriumManifold1D(
        equilibriumState: number[],
        settings: EquilibriumManifold1DSettings,
        mapIterations?: number
    ): EquilibriumManifold1DResult {
        const runner = this.createEquilibriumManifold1DRunner(
            equilibriumState,
            settings,
            mapIterations
        );
        return this.runManifoldRunnerToCompletion(runner);
    }

    runEquilibriumManifold2D(
        equilibriumState: number[],
        settings: EquilibriumManifold2DSettings
    ): EquilibriumManifold2DResult {
        const runner = this.createEquilibriumManifold2DRunner(equilibriumState, settings);
        return this.runManifoldRunnerToCompletion(runner);
    }

    runLimitCycleManifold2D(
        cycleState: number[],
        ntst: number,
        ncol: number,
        floquetMultipliers: ContinuationEigenvalue[],
        settings: LimitCycleManifold2DSettings
    ): LimitCycleManifold2DResult {
        const runner = this.createLimitCycleManifold2DRunner(
            cycleState,
            ntst,
            ncol,
            floquetMultipliers,
            settings
        );
        return this.runManifoldRunnerToCompletion(runner);
    }

    private runManifoldRunnerToCompletion<T>(runner: ManifoldRunner<T>): T {
        let progress = runner.get_progress();
        const batchSize = computeBatchSizeForRunner(progress.max_steps);

        while (!progress.done) {
            progress = runner.run_steps(batchSize);
        }

        return runner.get_result();
    }

    createHomoclinicContinuationRunner(
        setup: any,
        settings: any,
        forward: boolean
    ): ContinuationRunner {
        if (!wasmModule) throw new Error("WASM module not loaded");

        return new wasmModule.WasmHomoclinicRunner(
            this.config.equations,
            new Float64Array(this.config.params),
            this.config.paramNames,
            this.config.varNames,
            setup,
            settings,
            forward
        ) as ContinuationRunner;
    }

    createHomotopySaddleContinuationRunner(
        setup: any,
        settings: any,
        forward: boolean
    ): ContinuationRunner {
        if (!wasmModule) throw new Error("WASM module not loaded");

        return new wasmModule.WasmHomotopySaddleRunner(
            this.config.equations,
            new Float64Array(this.config.params),
            this.config.paramNames,
            this.config.varNames,
            setup,
            settings,
            forward
        ) as ContinuationRunner;
    }

    createContinuationExtensionRunner(
        branchData: ContinuationBranchData,
        parameterName: string,
        mapIterations: number,
        settings: any,
        forward: boolean
    ): ContinuationRunner {
        if (!wasmModule) throw new Error("WASM module not loaded");

        const useCodim1 = isCodim1BranchType((branchData as any)?.branch_type);
        const Runner = useCodim1
            ? wasmModule.WasmCodim1CurveExtensionRunner
            : wasmModule.WasmContinuationExtensionRunner;

        return new Runner(
            this.config.equations,
            new Float64Array(this.config.params),
            this.config.paramNames,
            this.config.varNames,
            this.config.type || "flow",
            mapIterations,
            branchData,
            parameterName,
            settings,
            forward
        ) as ContinuationRunner;
    }

    createFoldCurveRunner(
        foldState: number[],
        param1Name: string,
        param1Value: number,
        param2Name: string,
        param2Value: number,
        mapIterations: number,
        settings: any,
        forward: boolean
    ): Codim1CurveRunner {
        if (!wasmModule) throw new Error("WASM module not loaded");

        return new wasmModule.WasmFoldCurveRunner(
            this.config.equations,
            new Float64Array(this.config.params),
            this.config.paramNames,
            this.config.varNames,
            this.config.type || "flow",
            mapIterations,
            new Float64Array(foldState),
            param1Name,
            param1Value,
            param2Name,
            param2Value,
            settings,
            forward
        ) as Codim1CurveRunner;
    }

    createHopfCurveRunner(
        hopfState: number[],
        hopfOmega: number,
        param1Name: string,
        param1Value: number,
        param2Name: string,
        param2Value: number,
        mapIterations: number,
        settings: any,
        forward: boolean
    ): Codim1CurveRunner {
        if (!wasmModule) throw new Error("WASM module not loaded");

        return new wasmModule.WasmHopfCurveRunner(
            this.config.equations,
            new Float64Array(this.config.params),
            this.config.paramNames,
            this.config.varNames,
            this.config.type || "flow",
            mapIterations,
            new Float64Array(hopfState),
            hopfOmega,
            param1Name,
            param1Value,
            param2Name,
            param2Value,
            settings,
            forward
        ) as Codim1CurveRunner;
    }

    createLPCCurveRunner(
        lcState: number[],
        period: number,
        param1Name: string,
        param1Value: number,
        param2Name: string,
        param2Value: number,
        ntst: number,
        ncol: number,
        normalizedMesh: number[],
        settings: any,
        forward: boolean
    ): Codim1CurveRunner {
        if (!wasmModule) throw new Error("WASM module not loaded");

        return new wasmModule.WasmLPCCurveRunner(
            this.config.equations,
            new Float64Array(this.config.params),
            this.config.paramNames,
            this.config.varNames,
            new Float64Array(lcState),
            period,
            param1Name,
            param1Value,
            param2Name,
            param2Value,
            ntst,
            ncol,
            new Float64Array(normalizedMesh),
            settings,
            forward
        ) as Codim1CurveRunner;
    }

    createIsoperiodicCurveRunner(
        lcState: number[],
        period: number,
        param1Name: string,
        param1Value: number,
        param2Name: string,
        param2Value: number,
        ntst: number,
        ncol: number,
        normalizedMesh: number[],
        settings: any,
        forward: boolean
    ): Codim1CurveRunner {
        if (!wasmModule) throw new Error("WASM module not loaded");
        if (typeof wasmModule.WasmIsoperiodicCurveRunner !== 'function') {
            throw new Error(
                "Isoperiodic curve continuation runner is unavailable in this WASM build. Rebuild fork_wasm with `wasm-pack build --target nodejs`."
            );
        }

        return new wasmModule.WasmIsoperiodicCurveRunner(
            this.config.equations,
            new Float64Array(this.config.params),
            this.config.paramNames,
            this.config.varNames,
            new Float64Array(lcState),
            period,
            param1Name,
            param1Value,
            param2Name,
            param2Value,
            ntst,
            ncol,
            new Float64Array(normalizedMesh),
            settings,
            forward
        ) as Codim1CurveRunner;
    }

    createPDCurveRunner(
        lcState: number[],
        period: number,
        param1Name: string,
        param1Value: number,
        param2Name: string,
        param2Value: number,
        ntst: number,
        ncol: number,
        normalizedMesh: number[],
        settings: any,
        forward: boolean
    ): Codim1CurveRunner {
        if (!wasmModule) throw new Error("WASM module not loaded");

        return new wasmModule.WasmPDCurveRunner(
            this.config.equations,
            new Float64Array(this.config.params),
            this.config.paramNames,
            this.config.varNames,
            new Float64Array(lcState),
            period,
            param1Name,
            param1Value,
            param2Name,
            param2Value,
            ntst,
            ncol,
            new Float64Array(normalizedMesh),
            settings,
            forward
        ) as Codim1CurveRunner;
    }

    createNSCurveRunner(
        lcState: number[],
        period: number,
        param1Name: string,
        param1Value: number,
        param2Name: string,
        param2Value: number,
        initialK: number,
        ntst: number,
        ncol: number,
        normalizedMesh: number[],
        settings: any,
        forward: boolean
    ): Codim1CurveRunner {
        if (!wasmModule) throw new Error("WASM module not loaded");

        return new wasmModule.WasmNSCurveRunner(
            this.config.equations,
            new Float64Array(this.config.params),
            this.config.paramNames,
            this.config.varNames,
            new Float64Array(lcState),
            period,
            param1Name,
            param1Value,
            param2Name,
            param2Value,
            initialK,
            ntst,
            ncol,
            new Float64Array(normalizedMesh),
            settings,
            forward
        ) as Codim1CurveRunner;
    }

    createLyapunovRunner(
        startState: number[],
        startTime: number,
        steps: number,
        dt: number,
        qrStride: number
    ): AnalysisRunner<number[]> {
        if (!wasmModule) throw new Error("WASM module not loaded");

        return new wasmModule.WasmLyapunovRunner(
            this.config.equations,
            new Float64Array(this.config.params),
            this.config.paramNames,
            this.config.varNames,
            this.config.solver,
            new Float64Array(startState),
            startTime,
            steps,
            dt,
            qrStride
        ) as AnalysisRunner<number[]>;
    }

    createCovariantLyapunovRunner(
        startState: number[],
        startTime: number,
        dt: number,
        qrStride: number,
        windowSteps: number,
        forwardTransient: number,
        backwardTransient: number
    ): AnalysisRunner<CovariantLyapunovResponse> {
        if (!wasmModule) throw new Error("WASM module not loaded");

        return new wasmModule.WasmCovariantLyapunovRunner(
            this.config.equations,
            new Float64Array(this.config.params),
            this.config.paramNames,
            this.config.varNames,
            this.config.solver,
            new Float64Array(startState),
            startTime,
            dt,
            qrStride,
            windowSteps,
            forwardTransient,
            backwardTransient
        ) as AnalysisRunner<CovariantLyapunovResponse>;
    }

    createEquilibriumSolverRunner(
        initialGuess: number[],
        maxSteps: number,
        dampingFactor: number,
        mapIterations: number
    ): EquilibriumSolverRunner {
        if (!wasmModule) throw new Error("WASM module not loaded");

        return new wasmModule.WasmEquilibriumSolverRunner(
            this.config.equations,
            new Float64Array(this.config.params),
            this.config.paramNames,
            this.config.varNames,
            this.config.type || "flow",
            mapIterations,
            new Float64Array(initialGuess),
            maxSteps,
            dampingFactor,
            new Float64Array(periodicPeriodsForConfig(this.config))
        ) as EquilibriumSolverRunner;
    }

    set_state(state: number[]) {
        this.instance.set_state(new Float64Array(state));
    }

    get_state(): number[] {
        return Array.from(this.instance.get_state());
    }

    step(dt: number) {
        this.instance.step(dt);
    }

    get_t(): number {
        return this.instance.get_t();
    }

    set_t(t: number) {
        this.instance.set_t(t);
    }

    compute_jacobian(): number[] {
        return Array.from(this.instance.compute_jacobian());
    }

    solve_equilibrium(initialGuess: number[], maxSteps: number, dampingFactor: number, mapIterations: number): EquilibriumSolution {
        const result = this.instance.solve_equilibrium(
            new Float64Array(initialGuess),
            maxSteps,
            dampingFactor,
            mapIterations
        );
        return result as EquilibriumSolution;
    }

    computeLyapunovExponents(
        startState: number[],
        startTime: number,
        steps: number,
        dt: number,
        qrStride: number
    ): number[] {
        const result = this.instance.compute_lyapunov_exponents(
            new Float64Array(startState),
            startTime,
            steps,
            dt,
            qrStride
        );
        return Array.from(result);
    }

    computeCovariantLyapunovVectors(
        startState: number[],
        startTime: number,
        windowSteps: number,
        dt: number,
        qrStride: number,
        forwardTransient: number,
        backwardTransient: number
    ): CovariantLyapunovResponse {
        return this.instance.compute_covariant_lyapunov_vectors(
            new Float64Array(startState),
            startTime,
            windowSteps,
            dt,
            qrStride,
            forwardTransient,
            backwardTransient
        ) as CovariantLyapunovResponse;
    }

    compute_continuation(
        equilibriumState: number[],
        parameterName: string,
        mapIterations: number,
        settings: any,
        forward: boolean
    ): ContinuationBranchData {
        return this.instance.compute_continuation(
            new Float64Array(equilibriumState),
            parameterName,
            mapIterations,
            settings,
            forward
        ) as ContinuationBranchData;
    }

    extend_continuation(
        branchData: any,
        parameterName: string,
        mapIterations: number,
        settings: any,
        forward: boolean
    ): ContinuationBranchData {


        // Normalize branch_type for Wasm (Rust expects internally tagged enum)
        const normalizedBranch = { ...branchData };

        // Debugging: Log what we are receiving
        // console.log("Extending branch with type:", normalizedBranch.branch_type);

        if (typeof normalizedBranch.branch_type === 'string') {
            const typeStr = (normalizedBranch.branch_type as string).toLowerCase();

            if (typeStr === 'equilibrium') {
                normalizedBranch.branch_type = { type: 'Equilibrium' };
            } else if (typeStr === 'limit_cycle') {
                // Attempt to recover LC config if possible, or assume it's lost and this will fail later
                // But typically LC branches are created with objects.
                // This handles legacy/string cases if any exist.
                // For now, if it's 'limit_cycle' string, we can't easily reconstruct without ntst/ncol.
                // Assuming standard flow creates objects.
            }
        } else if (!normalizedBranch.branch_type) {
            // Default to Equilibrium if missing

            normalizedBranch.branch_type = { type: 'Equilibrium' };
        }



        return this.instance.extend_continuation(
            normalizedBranch,
            parameterName,
            mapIterations,
            settings,
            forward
        ) as ContinuationBranchData;
    }

    compute_limit_cycle_from_hopf(
        hopfState: number[],
        hopfParam: number,
        parameterName: string,
        methodRequest: any,
        amplitude: number,
        settings: any,
        forward: boolean
    ): LimitCycleBranchResponse {
        const continueFromHopf = this.instance.continue_limit_cycle_from_hopf;
        if (typeof continueFromHopf !== "function") {
            throw new Error(
                "Legacy limit-cycle continuation is unavailable in this WASM build."
            );
        }
        return continueFromHopf.call(
            this.instance,
            new Float64Array(hopfState),
            hopfParam,
            parameterName,
            methodRequest,
            amplitude,
            settings,
            forward
        ) as LimitCycleBranchResponse;
    }

    extend_limit_cycle_branch(
        branchData: any,
        parameterName: string,
        meta: LimitCycleMeta,
        settings: any,
        forward: boolean
    ): LimitCycleBranchResponse {
        const extendBranch = this.instance.extend_limit_cycle_branch;
        if (typeof extendBranch !== "function") {
            throw new Error(
                "Legacy limit-cycle branch extension is unavailable in this WASM build."
            );
        }
        return extendBranch.call(
            this.instance,
            branchData,
            parameterName,
            meta,
            settings,
            forward
        ) as LimitCycleBranchResponse;
    }

    computeEigenvalues(state: number[], parameterName: string, mapIterations: number, paramValue: number): ContinuationEigenvalue[] {
        const raw = this.instance.compute_equilibrium_eigenvalues(
            new Float64Array(state),
            parameterName,
            mapIterations,
            paramValue
        );
        return normalizeEigenvalues(raw);
    }

    /**
     * Initializes a limit cycle guess from a Hopf bifurcation point.
     */
    initLCFromHopf(
        hopfState: number[],
        parameterName: string,
        paramValue: number,
        amplitude: number,
        ntst: number,
        ncol: number
    ): any {
        return this.instance.init_lc_from_hopf(
            new Float64Array(hopfState),
            parameterName,
            paramValue,
            amplitude,
            ntst,
            ncol
        );
    }

    initLPCFromGeneralizedHopf(args: {
        ghState: number[];
        neighborState: number[];
        param1Name: string;
        param2Name: string;
        ghParam1: number;
        ghParam2: number;
        neighborParam1: number;
        neighborParam2: number;
        ghKappa: number;
        neighborKappa: number;
        neighborL1: number;
        secondLyapunov: number;
        amplitude: number;
        ntst: number;
        ncol: number;
        tolerance: number;
    }): any {
        return this.instance.init_lpc_from_generalized_hopf(
            new Float64Array(args.ghState),
            new Float64Array(args.neighborState),
            args.param1Name,
            args.param2Name,
            args.ghParam1,
            args.ghParam2,
            args.neighborParam1,
            args.neighborParam2,
            args.ghKappa,
            args.neighborKappa,
            args.neighborL1,
            args.secondLyapunov,
            args.amplitude,
            args.ntst,
            args.ncol,
            args.tolerance
        );
    }

    initCurvesFromBogdanovTakens(
        state: number[],
        param1Name: string,
        param2Name: string,
        param1Value: number,
        param2Value: number,
        perturbation: number,
        tolerance: number
    ): any {
        return this.instance.init_curves_from_bogdanov_takens(
            new Float64Array(state),
            param1Name,
            param2Name,
            param1Value,
            param2Value,
            perturbation,
            tolerance
        );
    }

    initHomoclinicFromBogdanovTakens(
        state: number[],
        param1Name: string,
        param2Name: string,
        param1Value: number,
        param2Value: number,
        perturbation: number,
        ntst: number,
        ncol: number,
        tolerance: number
    ): any {
        return this.instance.init_homoclinic_from_bogdanov_takens(
            new Float64Array(state),
            param1Name,
            param2Name,
            param1Value,
            param2Value,
            perturbation,
            ntst,
            ncol,
            tolerance
        );
    }

    /**
     * Initializes a limit cycle guess from a computed orbit.
     * The orbit should have converged to a stable limit cycle.
     * 
     * @param orbitTimes - Time values from the orbit
     * @param orbitStates - State vectors at each time point (as 2D array)
     * @param paramValue - Current value of the continuation parameter
     * @param ntst - Number of mesh intervals
     * @param ncol - Collocation points per interval
     * @param tolerance - Tolerance for cycle detection (recurrence)
     */
    initLCFromOrbit(
        orbitTimes: number[],
        orbitStates: number[][],
        paramValue: number,
        ntst: number,
        ncol: number,
        tolerance: number
    ): any {
        // Flatten the 2D orbit states into 1D array
        const flatStates = orbitStates.flat();

        return this.instance.init_lc_from_orbit(
            new Float64Array(orbitTimes),
            new Float64Array(flatStates),
            paramValue,
            ntst,
            ncol,
            tolerance
        );
    }

    /**
     * Initializes a period-doubled limit cycle from a period-doubling bifurcation.
     * Takes the LC state at the PD point and constructs a doubled-period initial guess.
     * 
     * @param lcState - Flattened collocation state at the PD point [mesh, stages, period]
     * @param parameterName - Name of the continuation parameter
     * @param paramValue - Parameter value at the PD point
     * @param ntst - Number of mesh intervals in the source LC
     * @param ncol - Collocation points per interval
     * @param amplitude - Perturbation amplitude for stepping onto the new branch
     */
    initLCFromPD(
        lcState: number[],
        parameterName: string,
        paramValue: number,
        ntst: number,
        ncol: number,
        normalizedMesh: number[],
        amplitude: number
    ): any {
        return this.instance.init_lc_from_pd_on_mesh(
            new Float64Array(lcState),
            parameterName,
            paramValue,
            ncol,
            new Float64Array(normalizedMesh),
            amplitude
        );
    }

    /**
     * Initializes a period-doubled map cycle seed from a period-doubling point.
     *
     * @param pdState - State at the PD point
     * @param parameterName - Name of the continuation parameter
     * @param paramValue - Parameter value at the PD point
     * @param mapIterations - Cycle length of the source branch
     * @param amplitude - Perturbation amplitude for stepping onto the new branch
     */
    initMapCycleFromPD(
        pdState: number[],
        parameterName: string,
        paramValue: number,
        mapIterations: number,
        amplitude: number
    ): number[] {
        return this.instance.init_map_cycle_from_pd(
            new Float64Array(pdState),
            parameterName,
            paramValue,
            mapIterations,
            amplitude
        ) as number[];
    }

    /**
     * Continues a limit cycle from an initial guess.
     */
    continueLimitCycle(
        setup: any,
        parameterName: string,
        settings: any,
        forward: boolean
    ): ContinuationBranchData {
        return this.instance.compute_limit_cycle_continuation(
            setup,
            parameterName,
            settings,
            forward
        ) as ContinuationBranchData;
    }

    initHomoclinicFromLargeCycle(
        lcState: number[],
        sourceNtst: number,
        sourceNcol: number,
        parameterName: string,
        param2Name: string,
        targetNtst: number,
        targetNcol: number,
        freeTime: boolean,
        freeEps0: boolean,
        freeEps1: boolean
    ): any {
        return this.instance.init_homoclinic_from_large_cycle(
            new Float64Array(lcState),
            sourceNtst,
            sourceNcol,
            parameterName,
            param2Name,
            targetNtst,
            targetNcol,
            freeTime,
            freeEps0,
            freeEps1
        );
    }

    initHomoclinicFromHomoclinic(
        pointState: number[],
        sourceNtst: number,
        sourceNcol: number,
        sourceFreeTime: boolean,
        sourceFreeEps0: boolean,
        sourceFreeEps1: boolean,
        sourceFixedTime: number,
        sourceFixedEps0: number,
        sourceFixedEps1: number,
        parameterName: string,
        param2Name: string,
        targetNtst: number,
        targetNcol: number,
        freeTime: boolean,
        freeEps0: boolean,
        freeEps1: boolean
    ): any {
        return this.instance.init_homoclinic_from_homoclinic(
            new Float64Array(pointState),
            sourceNtst,
            sourceNcol,
            sourceFreeTime,
            sourceFreeEps0,
            sourceFreeEps1,
            sourceFixedTime,
            sourceFixedEps0,
            sourceFixedEps1,
            parameterName,
            param2Name,
            targetNtst,
            targetNcol,
            freeTime,
            freeEps0,
            freeEps1
        );
    }

    initHomotopySaddleFromEquilibrium(
        equilibriumState: number[],
        parameterName: string,
        param2Name: string,
        ntst: number,
        ncol: number,
        eps0: number,
        eps1: number,
        time: number,
        eps1Tol: number
    ): any {
        return this.instance.init_homotopy_saddle_from_equilibrium(
            new Float64Array(equilibriumState),
            parameterName,
            param2Name,
            ntst,
            ncol,
            eps0,
            eps1,
            time,
            eps1Tol
        );
    }

    initHomoclinicFromHomotopySaddle(
        stageDState: number[],
        sourceNtst: number,
        sourceNcol: number,
        parameterName: string,
        param2Name: string,
        targetNtst: number,
        targetNcol: number,
        freeTime: boolean,
        freeEps0: boolean,
        freeEps1: boolean
    ): any {
        return this.instance.init_homoclinic_from_homotopy_saddle(
            new Float64Array(stageDState),
            sourceNtst,
            sourceNcol,
            parameterName,
            param2Name,
            targetNtst,
            targetNcol,
            freeTime,
            freeEps0,
            freeEps1
        );
    }

    continueHomoclinic(
        setup: any,
        settings: any,
        forward: boolean
    ): ContinuationBranchData {
        return this.instance.compute_homoclinic_continuation(
            setup,
            settings,
            forward
        ) as ContinuationBranchData;
    }

    continueHomotopySaddle(
        setup: any,
        settings: any,
        forward: boolean
    ): ContinuationBranchData {
        return this.instance.compute_homotopy_saddle_continuation(
            setup,
            settings,
            forward
        ) as ContinuationBranchData;
    }

    /**
     * Continues a fold (saddle-node) bifurcation curve in two-parameter space.
     * 
     * @param foldState - State vector at the fold bifurcation point
     * @param param1Name - Name of first active parameter
     * @param param1Value - Value of first parameter at fold point
     * @param param2Name - Name of second active parameter
     * @param param2Value - Value of second parameter at fold point
     * @param settings - Continuation settings
     * @param forward - Direction of continuation
     * @returns Codim-1 curve branch data
     */
    continueFoldCurve(
        foldState: number[],
        param1Name: string,
        param1Value: number,
        param2Name: string,
        param2Value: number,
        settings: any,
        forward: boolean
    ): any {
        return this.instance.continue_fold_curve(
            new Float64Array(foldState),
            param1Name,
            param1Value,
            param2Name,
            param2Value,
            1,
            settings,
            forward
        );
    }

    /**
     * Continues a Hopf bifurcation curve in two-parameter space.
     * 
     * @param hopfState - State vector at the Hopf bifurcation point
     * @param hopfOmega - Hopf frequency (imaginary part of critical eigenvalue)
     * @param param1Name - Name of first active parameter
     * @param param1Value - Value of first parameter at Hopf point
     * @param param2Name - Name of second active parameter
     * @param param2Value - Value of second parameter at Hopf point
     * @param settings - Continuation settings
     * @param forward - Direction of continuation
     * @returns Codim-1 curve branch data
     */
    continueHopfCurve(
        hopfState: number[],
        hopfOmega: number,
        param1Name: string,
        param1Value: number,
        param2Name: string,
        param2Value: number,
        settings: any,
        forward: boolean
    ): any {
        return this.instance.continue_hopf_curve(
            new Float64Array(hopfState),
            hopfOmega,
            param1Name,
            param1Value,
            param2Name,
            param2Value,
            1,
            settings,
            forward
        );
    }

    /**
     * Continues an LPC (Limit Point of Cycles) curve in two-parameter space.
     */
    continueLPCCurve(
        lcState: number[],
        period: number,
        param1Name: string,
        param1Value: number,
        param2Name: string,
        param2Value: number,
        ntst: number,
        ncol: number,
        settings: any,
        forward: boolean
    ): any {
        return this.instance.continue_lpc_curve(
            new Float64Array(lcState),
            period,
            param1Name,
            param1Value,
            param2Name,
            param2Value,
            ntst,
            ncol,
            settings,
            forward
        );
    }

    /**
     * Continues an isoperiodic curve in two-parameter space.
     */
    continueIsoperiodicCurve(
        lcState: number[],
        period: number,
        param1Name: string,
        param1Value: number,
        param2Name: string,
        param2Value: number,
        ntst: number,
        ncol: number,
        settings: any,
        forward: boolean
    ): any {
        if (typeof this.instance.continue_isoperiodic_curve !== 'function') {
            throw new Error(
                "Isoperiodic curve continuation is unavailable in this WASM build. Rebuild fork_wasm with `wasm-pack build --target nodejs`."
            );
        }
        return this.instance.continue_isoperiodic_curve(
            new Float64Array(lcState),
            period,
            param1Name,
            param1Value,
            param2Name,
            param2Value,
            ntst,
            ncol,
            settings,
            forward
        );
    }

    /**
     * Continues a PD (Period-Doubling) curve in two-parameter space.
     */
    continuePDCurve(
        lcState: number[],
        period: number,
        param1Name: string,
        param1Value: number,
        param2Name: string,
        param2Value: number,
        ntst: number,
        ncol: number,
        settings: any,
        forward: boolean
    ): any {
        return this.instance.continue_pd_curve(
            new Float64Array(lcState),
            period,
            param1Name,
            param1Value,
            param2Name,
            param2Value,
            ntst,
            ncol,
            settings,
            forward
        );
    }

    /**
     * Continues an NS (Neimark-Sacker) curve in two-parameter space.
     */
    continueNSCurve(
        lcState: number[],
        period: number,
        param1Name: string,
        param1Value: number,
        param2Name: string,
        param2Value: number,
        initialK: number,
        ntst: number,
        ncol: number,
        settings: any,
        forward: boolean
    ): any {
        return this.instance.continue_ns_curve(
            new Float64Array(lcState),
            period,
            param1Name,
            param1Value,
            param2Name,
            param2Value,
            initialK,
            ntst,
            ncol,
            settings,
            forward
        );
    }

    computeMapNormalForm(
        state: number[],
        parameterName: string,
        parameterValue: number,
        mapIterations: number,
        normalFormType: 'BranchPoint' | 'PeriodDoubling' | 'NeimarkSacker'
    ): ComputedNormalForm {
        const paramIndex = this.config.paramNames.indexOf(parameterName);
        if (paramIndex < 0) throw new Error(`Unknown map parameter: ${parameterName}`);
        const method = (this.instance as any).compute_map_normal_form;
        if (typeof method !== 'function') throw new Error('Map normal forms are unavailable in this WASM build.');
        return method.call(
            this.instance,
            new Float64Array(state),
            paramIndex,
            parameterValue,
            Math.max(1, Math.trunc(mapIterations)),
            normalFormType
        ) as ComputedNormalForm;
    }

    computePeriodicNormalFormFromPackedState(
        state: number[],
        parameterName: string,
        parameterValue: number,
        collocationDegree: number,
        normalizedMesh: number[],
        normalFormType: 'BranchPoint' | 'PeriodDoubling' | 'NeimarkSacker'
    ): ComputedNormalForm {
        const paramIndex = this.config.paramNames.indexOf(parameterName);
        if (paramIndex < 0) throw new Error(`Unknown periodic-orbit parameter: ${parameterName}`);
        const method = (this.instance as any).compute_periodic_normal_form_from_packed_state;
        if (typeof method !== 'function') {
            throw new Error('Packed periodic normal forms are unavailable in this WASM build.');
        }
        return method.call(
            this.instance,
            new Float64Array(state),
            paramIndex,
            parameterValue,
            collocationDegree,
            new Float64Array(normalizedMesh),
            normalFormType
        ) as ComputedNormalForm;
    }

    switchPeriodicBranchFromPackedState(
        state: number[],
        parameterName: string,
        parameterValue: number,
        collocationDegree: number,
        normalizedMesh: number[],
        amplitude: number
    ): { normalForm: ComputedNormalForm; setup: unknown } {
        const paramIndex = this.config.paramNames.indexOf(parameterName);
        if (paramIndex < 0) throw new Error(`Unknown periodic-orbit parameter: ${parameterName}`);
        const method = (this.instance as any).switch_periodic_branch_from_packed_state;
        if (typeof method !== 'function') {
            throw new Error('Packed periodic branch switching is unavailable in this WASM build.');
        }
        return method.call(
            this.instance,
            new Float64Array(state),
            paramIndex,
            parameterValue,
            collocationDegree,
            new Float64Array(normalizedMesh),
            amplitude
        ) as { normalForm: ComputedNormalForm; setup: unknown };
    }

    computeZeroHopfNormalForm(
        state: number[],
        param1Name: string,
        param2Name: string,
        param1Value: number,
        param2Value: number,
        frequency: number
    ): ZeroHopfNormalForm {
        return this.computeEquilibriumCodim2NormalForm(
            'compute_zero_hopf_normal_form', state, param1Name, param2Name,
            param1Value, param2Value, frequency, 'ZeroHopf'
        ) as ZeroHopfNormalForm;
    }

    computeHopfHopfNormalForm(
        state: number[],
        param1Name: string,
        param2Name: string,
        param1Value: number,
        param2Value: number,
        frequency: number
    ): HopfHopfNormalForm {
        return this.computeEquilibriumCodim2NormalForm(
            'compute_hopf_hopf_normal_form', state, param1Name, param2Name,
            param1Value, param2Value, frequency, 'HopfHopf'
        ) as HopfHopfNormalForm;
    }

    switchFromEquilibriumCodim2(
        sourceType: 'ZeroHopf' | 'DoubleHopf',
        state: number[],
        param1Name: string,
        param2Name: string,
        param1Value: number,
        param2Value: number,
        frequency: number,
        curvePerturbation: number,
        cycleAmplitude: number,
        ntst: number,
        ncol: number,
        tolerance: number
    ): any {
        const param1Index = this.config.paramNames.indexOf(param1Name);
        const param2Index = this.config.paramNames.indexOf(param2Name);
        if (param1Index < 0 || param2Index < 0 || param1Index === param2Index) {
            throw new Error('Codimension-two switching requires two distinct parameters.');
        }
        const methodName = sourceType === 'ZeroHopf'
            ? 'switch_from_zero_hopf'
            : 'switch_from_hopf_hopf';
        const method = (this.instance as any)[methodName];
        if (typeof method !== 'function') throw new Error(`${sourceType} switching is unavailable in this WASM build.`);
        return method.call(
            this.instance,
            new Float64Array(state),
            param1Index,
            param2Index,
            param1Value,
            param2Value,
            frequency,
            curvePerturbation,
            cycleAmplitude,
            ntst,
            ncol,
            tolerance
        );
    }

    private computeEquilibriumCodim2NormalForm(
        methodName: string,
        state: number[],
        param1Name: string,
        param2Name: string,
        param1Value: number,
        param2Value: number,
        frequency: number,
        type: 'ZeroHopf' | 'HopfHopf'
    ): ZeroHopfNormalForm | HopfHopfNormalForm {
        const param1Index = this.config.paramNames.indexOf(param1Name);
        const param2Index = this.config.paramNames.indexOf(param2Name);
        if (param1Index < 0 || param2Index < 0 || param1Index === param2Index) {
            throw new Error('Codimension-two normal forms require two distinct parameters.');
        }
        const method = (this.instance as any)[methodName];
        if (typeof method !== 'function') throw new Error(`${type} normal forms are unavailable in this WASM build.`);
        return {
            ...method.call(
                this.instance,
                new Float64Array(state),
                param1Index,
                param2Index,
                param1Value,
                param2Value,
                frequency
            ),
            type
        } as ZeroHopfNormalForm | HopfHopfNormalForm;
    }
}

function isCodim1BranchType(branchType: any): boolean {
    if (!branchType || typeof branchType !== 'object') {
        return false;
    }
    const type = branchType.type;
    return (
        type === 'FoldCurve' ||
        type === 'HopfCurve' ||
        type === 'LPCCurve' ||
        type === 'IsoperiodicCurve' ||
        type === 'PDCurve' ||
        type === 'NSCurve'
    );
}

function computeBatchSizeForRunner(maxSteps: number): number {
    if (!Number.isFinite(maxSteps) || maxSteps <= 0) {
        return 1;
    }
    return Math.max(1, Math.ceil(maxSteps / 50));
}

function normalizeEigenvalues(raw: unknown): ContinuationEigenvalue[] {
    if (!raw) return [];
    if (Array.isArray(raw)) {
        if (raw.length === 0) return [];
        if (typeof raw[0] === "number") {
            const nums = raw as number[];
            const result: ContinuationEigenvalue[] = [];
            for (let i = 0; i < nums.length; i += 2) {
                result.push({
                    re: nums[i] ?? 0,
                    im: nums[i + 1] ?? 0
                });
            }
            return result;
        }
        return raw.map((val: any) => {
            if (Array.isArray(val) && val.length >= 2) {
                return {
                    re: typeof val[0] === "number" ? val[0] : 0,
                    im: typeof val[1] === "number" ? val[1] : 0
                };
            }
            return {
                re: typeof val?.re === "number" ? val.re : Number(val?.re ?? 0),
                im: typeof val?.im === "number" ? val.im : Number(val?.im ?? 0)
            };
        });
    }

    if (ArrayBuffer.isView(raw)) {
        const nums = Array.from(raw as unknown as ArrayLike<number>);
        const result: ContinuationEigenvalue[] = [];
        for (let i = 0; i < nums.length; i += 2) {
            result.push({
                re: nums[i] ?? 0,
                im: nums[i + 1] ?? 0
            });
        }
        return result;
    }

    return [];
}
